name: iOS starter workflow

on:
  push:
    branches: [ "benchmark" ]

jobs:
  build:
    name: Run Benchmarks
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run benchmark tests
        run: | 
          sh benchmark.sh > /tmp/benchmark.log
